# Uncomment the next line to define a global platform for your project
#platform :ios, '13.2'

target 'Flamingo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'RealmSwift'
  pod 'Firebase/Storage'
  pod 'GTMSessionFetcher' 
end
